### ISSUE TITLE
How to set default value for custom attributes?

### ISSUE THREAD

**Issue by trietbui85** [pavel163/AttributesDispatcher#1]
For example, if we don't declare `app:custom_color="@android:color/holo_blue_light"`, how can I set default text color (in Java code) to `Color.RED` instead?

**Comment by pavel163** [comment]
@anticafe The default text color is specified in the theme. But I understand what the problem is. I completed yet after the holidays

**Comment by pavel163** [comment]
@anticafe the problem is solved in the release 1.1.0
