### ISSUE TITLE
Layout with same custom views won't dispatch values correctly

### ISSUE THREAD

**Issue by ersin-ertan** [pavel163/AttributesDispatcher#2]
```
 <com.m.myView
      android:id="@+id/id0"
      app:my_title="@string/stringA"
      />
 <com.m.myView
      android:id="@+id/id1"
      app:my_title="@string/stringB"
      />
```
Initial load of two views in the same layout, but with different ids, works correctly, however after rotation, the view `id1` along with the view `id0`, will receive the `id1`'s `stringB` value.

**Comment by pavel163** [comment]
@ersin-ertan Show your code, please. I can not reproduce it in my example

**Comment by ersin-ertan** [comment]
Please disregard, this is not an issue of the lib, sorry.
